name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, mnestic]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          clean: false
      - name: Copy docker-compose.yml
        run: cp /home/alan/Code/mnestic/docker-compose.yml docker-compose.yml
      - name: Deploy
        run: bash scripts/deploy.sh
